-- PES 2026 V1.7.4 - Club database, logo URLs and match snapshots
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  league text not null,
  team text not null,
  overall integer not null check (overall between 1 and 100),
  defence integer, midfield integer, attack integer, speed integer, strength integer,
  total_stats integer,
  average_stats numeric(8,2),
  power_score numeric(8,2),
  tier text,
  logo_file text,
  logo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teams_league_team_unique unique (league, team)
);

create index if not exists idx_teams_active_overall on public.teams(is_active, overall);
create index if not exists idx_teams_tier on public.teams(tier);

alter table public.match_rooms add column if not exists host_team_overall integer;
alter table public.match_rooms add column if not exists guest_team_overall integer;
alter table public.match_rooms add column if not exists host_team_logo_url text;
alter table public.match_rooms add column if not exists guest_team_logo_url text;

alter table public.matches add column if not exists team1_overall integer;
alter table public.matches add column if not exists team2_overall integer;
alter table public.matches add column if not exists team1_logo_url text;
alter table public.matches add column if not exists team2_logo_url text;

-- Allow the server-side app to read active teams. Adjust policies if RLS is enabled.
alter table public.teams enable row level security;
drop policy if exists "Public can read active teams" on public.teams;
create policy "Public can read active teams" on public.teams for select using (is_active = true);
